# Generated by Django 3.1.2 on 2020-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebook',
            name='rom',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy xotira'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='rom',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy xotira'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='SD karta mavjudligi'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maksimal tashqi xotira'),
        ),
    ]
