# Generated by Django 3.1.2 on 2020-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201018_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Umumiy narx'),
        ),
    ]
