# Generated by Django 3.1.2 on 2020-10-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20201020_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Umumiy narx'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Umumiy narx'),
        ),
    ]
