# Generated by Django 3.1.2 on 2020-10-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20201020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Umumiy narx'),
        ),
    ]
